#!/usr/bin/env bash
# set -x # Debug script

function Die()
{
    # Print exit message and exit shell
    # also print the trailing file as a convenience
    # example: Die "There was an error! Exiting." diagnosis_File
    echo "$*"
    [[ -f $2 ]] && echo "$2:" && cat "$2"
    exit 1
}

echo "Executing $0"
cd ${TUS}
echo "Running MemMap ..."
isolateDir="$(mktemp -dtp dceln/ MemMapSimDir-XXXXXX)"
./runOrDebug.sh -p dce --doNotCopy --force --isolate "${isolateDir##*/}" MemMap &> ${isolateDir}/runOutput || \
    Die " Couldn't run. See ${isolateDir}/run for output" ${isolateDir}/runOutput
# test delay
for n in ${isolateDir}/files-*/var/log/*/stdout; do
    [ -e "$n" ] && [ "$(tail -n 1 $n)" = "1-1--2-1--3-0--" ] \
	|| Die " MemMap did not equal the expected string."
done

rm -r "${isolateDir}"

echo "PASS"
